services:
  frontend:
    container_name: car-rental-frontend
    build: ./Frontend
    ports:
      - 3000:3000
  database:
    container_name: car-rental-database
    image: mariadb:10.3
    ports:
      - 3306:3306
    volumes:
      - ./Database/car_rental.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_rental
  backend:
    container_name: car-rental-backend
    build: ./Backend
    ports:
     - 8000:8000